"""add username unique index

Revision ID: a9d8e67ba756
Revises: 706635607abd
Create Date: 2025-01-13 11:44:30.420774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9d8e67ba756'
down_revision: Union[str, None] = '706635607abd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_service_user_username', 'service_user', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_service_user_username', 'service_user', type_='unique')
    # ### end Alembic commands ###
