"""add profile image

Revision ID: f04fa126fcab
Revises: dc1cb52c71ee
Create Date: 2025-01-10 15:00:12.091417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f04fa126fcab'
down_revision: Union[str, None] = 'dc1cb52c71ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_user', sa.Column('profile_image', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_user', 'profile_image')
    # ### end Alembic commands ###
