# Generated by Django 5.1.4 on 2024-12-11 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_addressesmodel_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addressesmodel',
            options={'verbose_name_plural': 'Addresses'},
        ),
    ]
